### ISSUE TITLE
where imgui

### ISSUE THREAD

**Issue by Mikquaj** [zoaq1/Pummed-CSGO-Source#1]
where imgui bro

**Comment by zoaq1** [comment]
idk i dont think pummed uses imgui

**Comment by Mikquaj** [comment]
![image](https://user-images.githubusercontent.com/81552040/145412613-71459d18-f205-42e3-bcb4-0d2a7c5e0ef1.png)

**Comment by zoaq1** [comment]
well im not a c# dev so

**Comment by Mikquaj** [comment]
> well im not a c# dev so

its cpp

**Comment by zoaq1** [comment]
exactly that proves my inexperience
